name: Update R DESCRIPTION dependencies

on:
  schedule:
    - cron: "0 2 * * 1"  # Every Monday at 2am UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bumpercar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run bumpercar
        uses: jahnen/bumpercar@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: master
