name: Bumpercar Dependency Update

on:
  push:
    branches: [main, master]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jahnen/bumpercar@v1.0.0
